#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DATA_ROOT="${ROBOT_KB_LOCAL_ROOT:-$HOME/Library/Application Support/RobotPokemonKB}"
RUNTIME_DIR="$DATA_ROOT/runtime-p3"
VENV_DIR="$DATA_ROOT/venv"
LOG_DIR="$HOME/Library/Logs/RobotPokemonKB"
P3_SHA="1d06fe33b6fc640657255e15a8d17251aa02b6ce"
APP_DB_USER="robotpokemon_kb"
KEYCHAIN_SERVICE="RobotPokemonKB.local-postgres"
LOCAL_DATABASE_URL="postgresql://robotpokemon_kb@127.0.0.1/robot_pokemon_kb"
MIGRATION_MARKER="$DATA_ROOT/MIGRATION_VERIFIED"

mkdir -p "$DATA_ROOT" "$LOG_DIR"
chmod 700 "$DATA_ROOT" "$LOG_DIR"

find_postgres_bin() {
  local candidate
  if command -v psql >/dev/null 2>&1 && command -v pg_isready >/dev/null 2>&1; then
    dirname "$(command -v psql)"
    return 0
  fi
  for candidate in \
    /Library/PostgreSQL/18/bin \
    /Library/PostgreSQL/17/bin \
    /Library/PostgreSQL/16/bin \
    /opt/homebrew/opt/postgresql@18/bin \
    /opt/homebrew/opt/postgresql@17/bin \
    /opt/homebrew/opt/postgresql@16/bin \
    /usr/local/opt/postgresql@18/bin \
    /usr/local/opt/postgresql@17/bin \
    /usr/local/opt/postgresql@16/bin; do
    if [ -x "$candidate/psql" ] && [ -x "$candidate/pg_isready" ]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

POSTGRES_BIN="$(find_postgres_bin || true)"

if ! command -v brew >/dev/null 2>&1; then
  if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [ -x /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
  else
    echo "Homebrew est requis uniquement pour Python 3.12. Installation officielle..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
fi
if [ -x /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x /usr/local/bin/brew ]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

if [ -z "$POSTGRES_BIN" ]; then
  echo "Aucune installation PostgreSQL existante détectée; installation Homebrew PostgreSQL 16..."
  brew list postgresql@16 >/dev/null 2>&1 || brew install postgresql@16
  brew services start postgresql@16 >/dev/null
  POSTGRES_BIN="$(brew --prefix postgresql@16)/bin"
else
  echo "PostgreSQL existant détecté : $POSTGRES_BIN"
fi
export PATH="$POSTGRES_BIN:$PATH"

for _ in {1..30}; do
  if pg_isready -h 127.0.0.1 >/dev/null 2>&1; then break; fi
  sleep 1
done
if ! pg_isready -h 127.0.0.1 >/dev/null 2>&1; then
  echo "PostgreSQL est installé mais le serveur local n'écoute pas sur 127.0.0.1:5432." >&2
  echo "Avec l'installateur PostgreSQL graphique, vérifie simplement que son service est démarré puis relance ce fichier." >&2
  exit 2
fi

brew list python@3.12 >/dev/null 2>&1 || brew install python@3.12
PY312="$(brew --prefix python@3.12)/bin/python3.12"

# Reuse the exact validated P3 Robot KB implementation instead of forking it.
echo "Préparation du runtime Robot KB validé ($P3_SHA)..."
git -C "$REPO_ROOT" fetch --quiet origin "$P3_SHA"
rm -rf "$RUNTIME_DIR"
mkdir -p "$RUNTIME_DIR"
git -C "$REPO_ROOT" archive "$P3_SHA" robot_kb requirements-postgres.txt requirements.txt | tar -x -C "$RUNTIME_DIR"

if [ ! -x "$VENV_DIR/bin/python" ]; then
  "$PY312" -m venv "$VENV_DIR"
fi
"$VENV_DIR/bin/python" -m pip install --quiet --upgrade pip
"$VENV_DIR/bin/python" -m pip install --quiet -r "$REPO_ROOT/requirements.txt" -r "$RUNTIME_DIR/requirements-postgres.txt"

# A dedicated local DB credential is generated by this installer and stored only
# in macOS Keychain. The user's PostgreSQL administrator password is never stored.
APP_PASSWORD="$(security find-generic-password -w -a "$APP_DB_USER" -s "$KEYCHAIN_SERVICE" 2>/dev/null || true)"
if [ -z "$APP_PASSWORD" ]; then
  APP_PASSWORD="$(openssl rand -hex 24)"

  ADMIN_ARGS=(-h 127.0.0.1 -d postgres)
  CREATEDB_ARGS=(-h 127.0.0.1)
  ADMIN_PASSWORD=""
  if ! psql "${ADMIN_ARGS[@]}" -Atqc 'SELECT 1' >/dev/null 2>&1; then
    echo
    printf "Utilisateur administrateur PostgreSQL local [postgres] : "
    IFS= read -r ADMIN_USER
    ADMIN_USER="${ADMIN_USER:-postgres}"
    printf "Mot de passe PostgreSQL local pour %s (entrée masquée) : " "$ADMIN_USER"
    IFS= read -r -s ADMIN_PASSWORD
    printf "\n"
    ADMIN_ARGS=(-h 127.0.0.1 -U "$ADMIN_USER" -d postgres)
    CREATEDB_ARGS=(-h 127.0.0.1 -U "$ADMIN_USER")
    export PGPASSWORD="$ADMIN_PASSWORD"
    if ! psql "${ADMIN_ARGS[@]}" -Atqc 'SELECT 1' >/dev/null 2>&1; then
      unset PGPASSWORD ADMIN_PASSWORD
      echo "Connexion administrateur PostgreSQL refusée. Aucun mot de passe n'a été enregistré." >&2
      exit 2
    fi
  fi

  role_exists="$(psql "${ADMIN_ARGS[@]}" -Atqc "SELECT 1 FROM pg_roles WHERE rolname='$APP_DB_USER'")"
  if [ "$role_exists" != "1" ]; then
    printf "CREATE ROLE %s LOGIN PASSWORD '%s';\n" "$APP_DB_USER" "$APP_PASSWORD" | psql "${ADMIN_ARGS[@]}" -v ON_ERROR_STOP=1 >/dev/null
  else
    printf "ALTER ROLE %s LOGIN PASSWORD '%s';\n" "$APP_DB_USER" "$APP_PASSWORD" | psql "${ADMIN_ARGS[@]}" -v ON_ERROR_STOP=1 >/dev/null
  fi

  db_exists="$(psql "${ADMIN_ARGS[@]}" -Atqc "SELECT 1 FROM pg_database WHERE datname='robot_pokemon_kb'")"
  if [ "$db_exists" != "1" ]; then
    createdb "${CREATEDB_ARGS[@]}" -O "$APP_DB_USER" robot_pokemon_kb
  else
    psql "${ADMIN_ARGS[@]}" -v ON_ERROR_STOP=1 -c "ALTER DATABASE robot_pokemon_kb OWNER TO $APP_DB_USER" >/dev/null
  fi

  security add-generic-password -U -a "$APP_DB_USER" -s "$KEYCHAIN_SERVICE" -w "$APP_PASSWORD" >/dev/null
  unset PGPASSWORD ADMIN_PASSWORD
fi
export PGPASSWORD="$APP_PASSWORD" PGUSER="$APP_DB_USER"

# An unverified local database may exist only if it is still empty. Any data in
# it without MIGRATION_VERIFIED is treated as unknown and blocks activation.
local_table_count="$(psql "$LOCAL_DATABASE_URL" -Atqc "SELECT count(*) FROM pg_tables WHERE schemaname NOT IN ('pg_catalog','information_schema')")"
if [ ! -f "$MIGRATION_MARKER" ] && [ "${local_table_count:-0}" -gt 0 ]; then
  echo "Une base locale non vide existe mais aucune migration Neon vérifiée n'est enregistrée." >&2
  echo "Collectors NON activés pour éviter de mélanger une base locale inconnue avec l'historique Neon." >&2
  exit 3
fi

if [ ! -f "$MIGRATION_MARKER" ]; then
  echo
  echo "Il faut d'abord copier l'historique Neon dans le Mac avant d'activer les collectors locaux."
  printf "Lancer la migration Neon maintenant ? [O/n] "
  IFS= read -r answer
  case "${answer:-O}" in
    n|N|non|NON)
      echo "Installation préparée, mais collectors NON activés pour éviter une base parallèle vide."
      echo "Lance ensuite : Migrer Robot KB Neon vers Mac.command, puis relance cet installateur."
      exit 0
      ;;
    *) /bin/bash "$SCRIPT_DIR/Migrer Robot KB Neon vers Mac.command" ;;
  esac
fi

if [ ! -f "$MIGRATION_MARKER" ]; then
  echo "Migration Neon non vérifiée; activation locale refusée." >&2
  exit 4
fi

export ROBOT_KB_DATABASE_URL="$LOCAL_DATABASE_URL"
/bin/bash "$SCRIPT_DIR/robot_kb_local_runner.sh" health

# Generate LaunchAgents without embedding credentials. The generated local DB
# password remains in macOS Keychain and is read by the runner at execution time.
"$VENV_DIR/bin/python" - "$SCRIPT_DIR/robot_kb_local_runner.sh" "$DATA_ROOT" "$LOG_DIR" "$HOME/Library/LaunchAgents" <<'PY'
import plistlib, sys
from pathlib import Path
runner, data_root, log_dir, agents_dir = map(Path, sys.argv[1:])
agents_dir.mkdir(parents=True, exist_ok=True)
base = {
    "ProcessType": "Background",
    "RunAtLoad": False,
    "LowPriorityIO": True,
    "EnvironmentVariables": {
        "ROBOT_KB_LOCAL_ROOT": str(data_root),
        "ROBOT_KB_DATABASE_URL": "postgresql://robotpokemon_kb@127.0.0.1/robot_pokemon_kb",
    },
}
def write(label, mode, schedule):
    payload = dict(base)
    payload.update({
        "Label": label,
        "ProgramArguments": ["/bin/bash", str(runner), mode],
        "StartCalendarInterval": schedule,
        "StandardOutPath": str(log_dir / f"{mode}.log"),
        "StandardErrorPath": str(log_dir / f"{mode}.err.log"),
    })
    path = agents_dir / f"{label}.plist"
    with path.open("wb") as handle:
        plistlib.dump(payload, handle, sort_keys=True)
    path.chmod(0o600)
    print(path)
write("com.robotpokemon.kb.fixed", "fixed", {"Minute": 32})
write("com.robotpokemon.kb.sold", "sold", [{"Minute": 17}, {"Minute": 47}])
write("com.robotpokemon.kb.backup", "backup", {"Hour": 3, "Minute": 10})
PY

for label in com.robotpokemon.kb.fixed com.robotpokemon.kb.sold com.robotpokemon.kb.backup; do
  plist="$HOME/Library/LaunchAgents/$label.plist"
  launchctl bootout "gui/$(id -u)" "$plist" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/$(id -u)" "$plist"
done

# Immediate catch-up after the verified migration; GET-only collectors, no commercial action.
echo "Rattrapage local initial fixed/auction..."
/bin/bash "$SCRIPT_DIR/robot_kb_local_runner.sh" fixed
echo "Rattrapage local initial SOLD..."
/bin/bash "$SCRIPT_DIR/robot_kb_local_runner.sh" sold
/bin/bash "$SCRIPT_DIR/robot_kb_local_runner.sh" health

unset PGPASSWORD APP_PASSWORD

echo
echo "Robot KB local est actif. Neon n'est plus nécessaire pour les nouvelles écritures."
echo "Données : $DATA_ROOT"
echo "Logs : $LOG_DIR"
